import Head from 'next/head'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>SPA Test Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="header">
        <a href="https://ribs.ai" target="_blank" className="header__logo" rel="noreferrer"></a>
      </header>

      <div className="container">
        <main className="main">{children}</main>
      </div>
    </>
  )
}
